[versions]
dokka = "1.7.20"
gradlePlugins-versionCatalog = "0.7.0"
kotest = "5.5.4"
kotlin = "1.8.0"
kotlin-html = "0.8.0"
kotlin-serialisation = "1.4.1"
nexus = "1.1.0"
versions = "0.44.0"

[libraries]
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlin-html" }
kotlinx-serialisation = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialisation" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
serialisation = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "gradlePlugins-versionCatalog" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
