name: Publish test report to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create test report
        run: ./gradlew test

      - name: Copy files
        run: cp ./gh-pages/.nojekyll ./gh-pages/* ./build/reports/kotest

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/kotest
